project:
  type: website
  output-dir: docs

website:
  title: "Joe Post | Spatial Analyst"
  navbar:
    left:
      - file: index.qmd
        text: "Home"
      - file: work.qmd
        text: "Work"
      # - file: shinyapps.qmd
      #   text: "Shiny Apps"
      - file: resume.qmd
        text: "Resume"
      - file: about.qmd
        text: "Contact"
    background: primary
    search: true
  google-analytics: "G-J5LRVPS2D6"

format:
  html:
    theme: flatly #litera
    fontsize: medium
    css: styles.css
    toc: true

editor: visual

