---
title: "Resume"
---

### Education

**MSc Urban Spatial Science** Bartlett Centre for Advanced Spatial Analysis (CASA), University College London, 2022 – 2023 (*results pending*).  

**BSc Honours, Epidemiology** Murdoch Children’s Research Institute (MCRI), The University of Melbourne, 2018 | First Class Honours.  

**BSc Environmental Science** The University of Melbourne, 2015 – 2017 | First Class Honours. 

**Student Exchange** The University of Helsinki, Finland, 2016. 


### Employment History

**Senior Analyst** Australian Institute of Health and Welfare (AIHW), Indigenous Data Improvements Unit, Canberra (Remote), Oct 2022 -- Present (*part-time while studying*)

-   Supporting the design and implementation of Australia's National Child Death Register, including data governance, research, development of metadata standards, and stakeholder engagement with state/territory authorities.  

**HIV Registry Project Lead** Alfred Hospital, Epidemiology & Data Management Service, Melbourne, Jan 2022 – Jul 2022  

-   Lead the development and implementation of the Victorian HIV Service's Clinical Quality Registry, a state-wide database and initiative to improve quality of care and coordinate standards across 12 Victorian hospitals and care providers.  

**COVID-19 Response Analyst** Victorian Department of Health, Data, Intelligence, Modelling and Epidemiology (DIME) branch, Melbourne, Oct – Dec 2021   

-   Secondment to the Department of Health to provide analytical support for the COVID-19 response. Data analysis/programming in R and SQL to produce routine and on-demand COVID-19 data reports, collaboratively build complex and high-volume data workflows, and troubleshoot errors and data discrepancies. 

**Clinical Data Officer** Alfred Hospital, Epidemiology & Data Management Service, Melbourne, Jan 2020 – Oct 2021  

-   Deputy Manager for a team of 6. Provided a broad range of database management, data analysis, and reporting for the clinical, research, and epidemiology activities of the Department of Infectious Diseases, including Infection Prevention and the Victorian HIV service. 
-   Delivered operational and analytical support for the Alfred Hospital's COVID-19 pandemic response, incl. the build and management of a bespoke database monitoring testing results and notifications.

**Data Analyst** Australian Institute of Health and Welfare (AIHW), Indigenous Spatial Analysis Unit, Canberra, Jan 2019 – Jan 2020.  

-   2019 AIHW Graduate Program. Worked across large national databases incl. the Medicare Benefits Schedule Dataset and Australian Bureau of Statistics Census Datalab, and contributed authoring, analysis, mapping (Esri ArcGIS), dashboard design, and validation to several major institute reports.  

**Research Assistant** Transport, Health, and Urban Design Research Hub, University of Melbourne, Aug 2017 – Jan 2019   

-   Conducted literature reviews, analysis, and operational support for Hub research projects.
-   Coordinated seminars, website management, communications, financial administration, and 
reporting and monitoring of research output and Hub KPIs. 


### Scholarships and Awards

-   Rae & Edith Bennett Prestigious Travelling Scholarship, 2022
-   University of Melbourne Dean’s Honour List, BSc (Hons), 2018
-   Murdoch Children’s Research Institute Honours Scholarship, 2018
-   Melbourne Global Mobility, Global Scholars Award, 2016
-   International House, University of Melbourne, General Residential Scholarship, 2015 – 2016
-   University of Melbourne Kwong Lee Dow Young Scholar, 2014
