---
title: "Interactive Maps"
---

## Spatial distribution of residential property prices, 1995 - 2019

This map visualises the spatial distribution of Lower Layer Super Output Areas (LSOA) median price paid deciles for residential property sold between 1995 and 2019, for the local authority district of Hackney, London.

Data is sourced entirely from API data services, including:

[Ordnance Survey (OS) Data Hub](https://osdatahub.os.uk/)

-   OS Features API - *allows user to query features within a number of OS's data products. An Open Geospatial Consortium (OGC) compliant web feature service (WFS).*

-   OS Maps API - *provides access to OS base mapping in a number of different styles and two projections, Web Mercator or British National Grid. Two end points are available: ZXY or Web Map Tile Service (WMTS).*

-   OS Downloads API - *enables bulk download of OS open data products.*

[HM Land Registry](https://landregistry.data.gov.uk/app/root/doc/ppd)

-   HM LR Linked Data API - *enables querying of HM LR price paid data, transaction data, and the UK House Price Index.*

[*Office for National Statistics (ONS)*](https://geoportal.statistics.gov.uk/)

-   ONS Open Geography Portal WFS API - *OGC-compliant WFS that allows users to query features within a number of ONS's open data products.*

-   ONS Open Geography Portal ArcGIS REST API - *an ESRI API specification that allows users to query features within ONS's open data products.*

```{python}
from ipyleaflet import Map, Marker, basemaps, basemap_to_tiles
m = Map(
  basemap=basemap_to_tiles(
    basemaps.NASAGIBS.ModisTerraTrueColorCR, "2017-04-08"
  ),
  center=(52.204793, 360.121558),
  zoom=4
)
m.add_layer(Marker(location=(52.204793, 360.121558)))
m
```

Test

-   List item 1

-   List item 2

-   List item 3

|                                           |                                                                                                                                                                                                  |
|-------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **Ordnance Survey (OS) Data Hub**         |                                                                                                                                                                                                  |
| OS Features API                           | Allows user to query features within a number of OS's data products. An Open Geospatial Consortium (OGC) compliant web feature service (WFS).                                                    |
| OS Maps API                               | Provides access to OS base mapping in a number of different styles and two projections, Web Mercator or British National Grid. Two end points are available: ZXY or Web Map Tile Service (WMTS). |
| OS Downloads API                          | Enables bulk download of OS open data products.                                                                                                                                                  |
| **HM Land Registry**                      |                                                                                                                                                                                                  |
| HM LR Linked Data API                     | Enables querying of HM LR price paid data, transaction data, and the UK House Price Index.                                                                                                       |
| **Office for National Statistics (ONS)**  |                                                                                                                                                                                                  |
| ONS Open Geography Portal WFS API         | OGC-compliant WFS that allows users to query features within a number of ONS's open data products.                                                                                               |
| ONS Open Geography Portal ArcGIS REST API | ESRI API specification that allows users to query features within ONS's open data products.                                                                                                      |
